artemis:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Individual Position Controllers ----------------------------
  # Allows to send individual ROS msg of Float64 to each joint separately
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Group Position Controllers ---------------------------------------
  # Allows to send single ROS msg of Float64MultiArray to all joints
  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2
