<?xml version="1.0"?>

<robot name="artemis" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="diameter1" value="0.8" />
  <xacro:property name="height1" value="0.5" />
  <xacro:property name="width" value="0.8" />
  <xacro:property name="height2" value="0.1" />
  <xacro:property name="length3" value="1.0" />
  <xacro:property name="width3" value="0.2" />
  <xacro:property name="height3" value="0.1" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <!-- <xacro:include filename="$(find artemis_description)/urdf/artemis.gazebo" /> -->

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find artemis_description)/urdf/materials.xacro" />

  <!-- Gazebo plugin for parsing transmission tags -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/artemis</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Used for fixing robot to Gazebo -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${height1}" radius="${diameter1/2}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${height1}" radius="${diameter1/2}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${height1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${height2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="${length3/2} 0 ${height3/2}" rpy="0 0 0"/>
      <geometry>
  	<box size="${length3} ${width3} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length3/2} 0 ${height3/2}" rpy="0 0 0"/>
      <geometry>
  	<box size="${length3} ${width3} ${height3}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
  	  ixx="${mass / 12.0 * (length3*width3 + height3*height3)}" ixy="0.0" ixz="0.0"
  	  iyy="${mass / 12.0 * (height3*height3 + length3*width3)}" iyz="0.0"
  	  izz="${mass / 12.0 * (length3*width3 + length3*width3)}"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
